version: '3.4'

services:
  app:
    restart: always
    container_name: run_js_web_prd
    image: run_js_web:latest
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - run_js_web_prd_network

networks:
  run_js_web_prd_network:
    external: false
